name: update
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: download workflows
        run: |
          curl https://raw.githubusercontent.com/weichware-10/repo-util/main/workflows/badges.yaml --output .github/workflows/badges.yaml
          curl https://raw.githubusercontent.com/weichware-10/repo-util/main/workflows/tests.yaml --output .github/workflows/tests.yaml
          curl https://raw.githubusercontent.com/weichware-10/repo-util/main/workflows/update.yaml --output .github/workflows/update.yaml
      - name: download checkstyle
        run: curl https://raw.githubusercontent.com/weichware-10/repo-util/main/checkstyle.xml --output checkstyle.xml
      - name: commit files
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: update from weichware-10/repo-utils
